# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef23fb4809ab90e46e80b5254d3d54208fa97c597b0ea26412d8a2b551460f326895ad14015d4fc4711d37c3428699c2617d9573b1350711ab98a3dfc3581b89

test:
  secret_key_base: 00c001eecdcf524b16e2f977852b6cf2d061637e441043490143af2c71dcb4cfefcc48eba5e4510da03d968ce167d32ae58769b813861c7d366b58848c8ebf6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
